spring.application.name=backEndSpringBoot
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DATN;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# JWT Configuration
api.key=b0a1e763e0d744a1bcc7bc9c2eb181fc
# JWT Configuration

jwt.secret=Hl+wa1/1bnThJLpEV3PoB+mdp3/gaPusNpE/69G9GhzMHaTgPb/G96o6qOLfWblI
jwt.refresh=cQEO67H+Q8NPAGKOeQUr8XhO0XFiacgwzQ69buaCUhuplVaD15O+s/J9zL7bSHNA
jwt.expiration=3600000


vonage.api_key=fad168f8
vonage.api_secret=ZZH8U8r5CvmnBxYi
google.client-id=310245911476-bb6s06ookc8aftr8b9lka1n30sl41ou7.apps.googleusercontent.com


zalopay.app-id=554
zalopay.key1=8NdU5pG5R2spGHGhyO99HN1OhD8IQJBn
zalopay.key2=uUfsWgfLkRLzq6W2uNXTCxrfxs51auny
zalopay.endpoint=https://sandbox.zalopay.com.vn/v001/tpe/createorder


spring.security.oauth2.resourceserver.jwt.issuer-uri=dev-twfkqnctlq4gaa4s.us.auth0.com
spring.security.oauth2.resourceserver.jwt.audiences=CZ3GqRaNIwkr0CP0j8H9MVoVsnai9T2z


