spring.application.name=backEndSpringBoot
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DATN;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# JWT Configuration
jwt.secret=GQa+v/ZWqhSG4UTa3u7R4kuEqC2vLfdtYN42sih/TOinIsW610x42IL/YrsyRTWV
jwt.expiration=3600000

vonage.api_key=fad168f8
vonage.api_secret=ZZH8U8r5CvmnBxYi

spring.security.oauth2.client.registration.google.client-id=411296136351-iaqdi70a79eusbgrs6f1or923ngmk7gh.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=profile,email

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=accessnameit@gmail.com
spring.mail.password=oyli twzn hyko cxrj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

zalopay.app-id=554
zalopay.key1=8NdU5pG5R2spGHGhyO99HN1OhD8IQJBn
zalopay.key2=uUfsWgfLkRLzq6W2uNXTCxrfxs51auny
zalopay.endpoint=https://sandbox.zalopay.com.vn/v001/tpe/createorder




spring:
security:
oauth2:
client:
registration:
google:
client-id: 411296136351-iaqdi70a79eusbgrs6f1or923ngmk7gh.apps.googleusercontent.com
client-secret: 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
server:
port:3000


